### ISSUE TITLE
Automatic connect to debugger mode after app run

### ISSUE THREAD

**Issue by matejdro** [Chimerapps/niddler-ui#12]
~It would be very useful if Niddler would offer automatic connection to the app after app is built and started on the device.~

Currently Niddler has an option to auto connect after Run, but this does not appear to activate Debug mode (rewrites).

**Comment by matejdro** [comment]
Nevermind, it looks like there is already a setting for that. However, setting always connects in run mode, not debug mode. I have updated description.

**Comment by NicolaChimerapps** [comment]
I see what you mean. I will have to think about how this can be specified UX-wise

**Comment by NicolaChimerapps** [comment]
I guess adding an extra checkbox works well enough for now (prepares for boolean trap in the future)

**Comment by NicolaChimerapps** [comment]
Version 2.9.4 is pending review by jetbrains
