### ISSUE TITLE
Changing debugger/rewrite properties requires reconnect to take effect 

### ISSUE THREAD

**Issue by matejdro** [Chimerapps/niddler-ui#20]
1. Start app with niddler
2. Connect Niddler in debug mode
3. Make some requests to ensure debug mode works
4. Change some rewrite properties (such as enabling/disabling some rules or changing properties of those rules)

Changes will not take effect. I have to disconnect and reconnect to make them stick. 

This is with Niddler UI 2.9.4 and Niddler 1.2.0 on Android app

**Comment by NicolaChimerapps** [comment]
Yes, this is a known omission that I still have to work on and/or document

**Comment by matejdro** [comment]
Maybe a good stopgap solution would be a popup after pressing OK button that would say "Changes will be applied after reconnect. Do you want to reconnect now?" with yes/no buttons.

**Comment by NicolaChimerapps** [comment]
The new implementation is far from optimal, but it does work. Expect to see this land in 2.9.5 when all administration has done it's job

**Comment by NicolaChimerapps** [comment]
2.9.5 is pending review by intellij
