### ISSUE TITLE
Niddler not auto connecting when starting app via debugger

### ISSUE THREAD

**Issue by matejdro** [Chimerapps/niddler-ui#23]
1. Enable "Automatically connect niddler when running option"
2. Instead of using "Run" button to start the app, use "Debug" button
3. Niddler will not auto-connect

This is with Android Studio 4.0 and Niddler-ui 2.9.5

**Comment by NicolaChimerapps** [comment]
It seems the output we capture from the debug launch is from the debugger itself, not the application, hence no logs. Investigation into what else we can do in progress

**Comment by NicolaChimerapps** [comment]
Best-effort fix using some regex heuristics will be in 2.9.6 which is pending review by JetBrains
