### ISSUE TITLE
Using Copy action in Niddler's details will prevent IntelliJ from using system clipboard

### ISSUE THREAD

**Issue by matejdro** [Chimerapps/niddler-ui#28]
I've noticed very weird bug with Niddler:

1. Open details of any request in Niddler
2. Right click on any header and select Copy (for example, this will copy `Content-Type` into clipboard)
3. Open any other application and copy text from there
4. Attempt to paste this into any field in IntelliJ

BUG: Instead of whatever you copied in step 3, Niddler's value will be pasted (in above example `Content-Type` will be pasted).

So basically, at this point, IntelliJ will stop reacting to any clipboard changes outside IntellIJ. It will keep clipboard at Niddler's copy.

Workaround for this is to select any text inside IntelliJ (for example inside text editor) and copy it - this will unblock the clipboard sync.

This is with:

Android Studio 4.1
Build #AI-201.8743.12.41.6858069, built on September 23, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.8.17-1-manjaro

(I know I said IntelliJ above, but Android Studio uses IntelliJ platform under the hood so I'm using them interchangeably)

Any ideas what could cause this?

**Comment by NicolaChimerapps** [comment]
Very curious, I am using the default clipboard utilities provided by the IDE. I tried to reproduce your issue on OSX and I could not reproduce it. It must be a platform/IntelliJ issue specific to your setup.

As I don't have the resources (time) to create a similar setup, I am unable to investigate this further at this time. Perhaps an IntelliJ bug would be in order.
