### ISSUE TITLE
Feature request: option to not open Niddler window when auto connecting

### ISSUE THREAD

**Issue by matejdro** [Chimerapps/niddler-ui#33]
Currently when Niddler is set to auto-connect, IDE will auto-switch to the Niddler window on every single run of the app.

That is pretty annoying, because most of the time I will not be needing Niddler right away.

Could you add an option to disable this behavior?

**Comment by NicolaVerbeeck** [comment]
I have been annoyed by this as well. The fix is not so simple though. I will continue this work when I find some spare time
